imports:
    - { resource: parameters.yaml }

framework:
    secret: "%secret%"
    templating:
        engines: ['twig']
    profiler:
        only_exceptions: false

twig:
    paths:
        '%kernel.root_dir%/../app/templates': app
